[template]
src = "switch_elastichd.sh.tmpl"
dest = "/opt/common/bin/switch_elastichd.sh"
keys = ["/",]
reload_cmd = "chmod +x /opt/common/bin/switch_elastichd.sh && /opt/common/bin/switch_elastichd.sh"
