[template]
src = "switch_elasticsearch_head.sh.tmpl"
dest = "/opt/common/bin/switch_elasticsearch_head.sh"
keys = ["/",]
reload_cmd = "chmod +x /opt/common/bin/switch_elasticsearch_head.sh && /opt/common/bin/switch_elasticsearch_head.sh"
